name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: "1.22.1"
          cache: false
      
      - name: Build geosite
        id: build_site
        run: |
          cd sing-geosite
          go run -v .
          sha256sum geosite.db > geosite.db.sha256sum
      
      - name: Build geoip
        id: build_ip
        run: |
          cd sing-geoip
          go run -v .
          sha256sum geoip.db > geoip.db.sha256sum
          sha256sum geoip-cn.db > geoip-cn.db.sha256sum
      
      - name: Release rule sets
        if: steps.build.outputs.skip != 'true'
        run: .github/release-rule-set.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current time
        id: time
        run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Create a release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            sing-geosite/geosite.db
            sing-geosite/geosite.db.sha256sum
            sing-geoip/geoip.db
            sing-geoip/geoip.db.sha256sum
            sing-geoip/geoip-cn.db
            sing-geoip/geoip-cn.db.sha256sum
